### ISSUE TITLE
Compatability problem with EF Core 2.1, Linq and Fielder

### ISSUE THREAD

**Issue by m-demydiuk** [Fody/Fielder#13]
Hi, I noticed strange Exception `EntryPointNotFoundException` when fielder package is installed in the project. It breaks EF Core/Linq `Select` statements. So we decided not to go to prod with fielder for now because we don't know what else it can break.

I created a test repository to reproduce this issue, you can find it following the link below:
https://github.com/m-demydiuk/FodyFielderLinqError

Just one test method `FielderLinq.FielderTests.GetUsers()`. I hope this test project will be enough input information. I cant give you more info, because I did not find any related in google.

Please advise. Thanks!

**Comment by SimonCropp** [comment]
can u try explicitly installing the newest version of fody https://github.com/Fody/Fielder#nuget-installation

**Comment by m-demydiuk** [comment]
I updated but still the same.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
