### ISSUE TITLE
After running Fielder, all resulting properties are ordered alphabetically

### ISSUE THREAD

**Issue by comstyle** [Fody/Fielder#6]
I really love Fielder and use it in a lot of projects.
But one thing I find is annoying, my fields which have a specific order on purpose are ordered alphabetically after I run Fielder.
Could you please add a switch to disable this or disable it as default.

Thank you very much

**Comment by SimonCropp** [comment]
Sounds good. Send me a pull request

**Comment by comstyle** [comment]
I started working on it and when I added unit tests I realized that Fielder doesn't change the order like I thought. It seems to be "Just Decompile" which does the ordering of properties.
type.GetProperties() gets the properties in the original order.
Sorry for bothering you.
Thank you very much for Fielder.
